apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
  labels:
    app: aspnet-core-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver
          image: receiver-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mnt
              mountPath: /config-data
      volumes:
        - name: mnt
          configMap:
            name: receiver-configmap
