apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
  labels:
    app: aspnet-core-app
  namespace: log
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
        - name: healthcheck
          image: healthcheck-api
          imagePullPolicy: Never
          ports:
            - containerPort: 80
