kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sql-server-pvc
  namespace: item
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
