apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  namespace: item
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-deployment
  template:
    metadata:
      labels:
        app: sqlserver-deployment
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
            limits:
              memory: "2G"
              cpu: "2000m"
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: password
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: sql-server-pvc
