providers:
  kubernetesCRD:
    namespaces:
      - default
  kubernetesIngress:
    namespaces:
      - default

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443

service:
  type: NodePort