version: "3.8"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQL_SERVER_PASSWORD # Replace on production
    volumes:
      - sqldata:/var/opt/mssql
    restart: on-failure
    networks:
      - forum-system-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      rtprio: 95
      memlock: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - forum-system-network

  forum-service:
    container_name: forum-service
    image: forum-service:1.0
    build:
      context: ./forum-service
      dockerfile: ./Dockerfile
    ports:
      - "?:80"
    env_file: Common.env
    restart: on-failure
    volumes:
      - ./.apsnet/forum-service/DataProtection-Keys:/root/.aspnet/forum-service/DataProtection-Keys
    networks:
      - forum-system-network
    depends_on:
      - sqlserver
      - elasticsearch

networks:
  forum-system-network:

volumes:
  sqlserver:
  elasticsearch:
